server:
  port: 8081

spring:
  application:
    name: client-consumer

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      client-group-id: client-consumer-group
      address-group-id: address-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: kafka-consumer-db

kafka:
  topics:
    client-events: client-events
    address-events: address-events

logging:
  level:
    org.springframework.data.mongodb: DEBUG